{{- if .Values.netbox.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "netbox-lab.fullname" . }}-netbox
  labels:
    {{- include "netbox-lab.labels" . | nindent 4 }}
  {{- with .Values.netbox.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.netbox.ingress.className }}
  ingressClassName: {{ .Values.netbox.ingress.className }}
  {{- end }}
  {{- if .Values.netbox.ingress.tls }}
  tls:
    {{- range .Values.netbox.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.netbox.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "netbox-lab.fullname" $ }}-netbox
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
