apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netbox-lab.fullname" . }}-reports
  labels:
    {{- include "netbox-lab.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.netbox.persistence.reports.storageClass }}
  storageClassName: {{ .Values.netbox.persistence.reports.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.netbox.persistence.reports.size }}
