apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox-lab.fullname" . }}-netbox
  labels:
    {{- include "netbox-lab.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  redis-tasks-password: {{ index .Values "redis-tasks" "auth" "password" | b64enc | quote }}
  redis-cache-password: {{ index .Values "redis-cache" "auth" "password" | b64enc | quote }}
  secret-key: {{ .Values.netbox.secretKey | b64enc | quote }}
  api-token-pepper: {{ .Values.netbox.apiTokenPepper | b64enc | quote }}
  superuser-password: {{ .Values.netbox.superuser.password | b64enc | quote }}
  superuser-api-token: {{ .Values.netbox.superuser.apiToken | b64enc | quote }}
